HOSTS:
  ubuntu-1404-x64:
    default_apply_opts:
      order: random
      strict_variables:
    platform: ubuntu-14.04-amd64
    hypervisor : docker
    image: ubuntu:14.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d'
      - 'rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl'
      - 'locale-gen en_US.UTF-8'
      - 'locale-gen de_CH.UTF-8'
CONFIG:
  type: aio
  log_level: debug
